### ISSUE TITLE
Test the accuracy of restarts in MP-Gadget

### ISSUE THREAD

**Issue by Chris-Pedersen** [andreufont/LyaCosmoParams#14]
If we are considering running simulations with more than 1024**3 particles this will involve restarting simulations due to DiRACs 24 hour walltime cap.

I will run a 512 on DiRAC and compare the z=2 output with 1, 2 and 3 restarts to see if there is any significant disagreement in the results of the final simulations.

**Comment by andreufont** [comment]
That would be great. Thanks!

**Comment by Chris-Pedersen** [comment]
Below are plots of the ratios of different power spectra at z=2 for 4 sims:

0 restarts
Restart at z=5
Restarts at z=5 and z=4
Restarts at z=5, z=4 and z=3

![BaryonRestart](https://user-images.githubusercontent.com/16047009/58432016-5b87d380-80a8-11e9-83e9-28bcafd96c70.png)
![CDMRestart](https://user-images.githubusercontent.com/16047009/58432020-5dea2d80-80a8-11e9-8953-a5333ac9c8e3.png)

P1D ratios with and without matching the mean fluxes. The mean fluxes in the simulations at z=2 are:

```
0 restarts: <F>= 0.888122, T0=12059.13, gamma=0.544545
1 restart:  <F>= 0.888070, T0=12058.30, gamma=0.545016
2 restarts: <F>= 0.887933, T0=12012.88, gamma=0.544453
3 restarts: <F>= 0.887891, T0=12009.67, gamma=0.544533
```

![restarts_p1d_diffF](https://user-images.githubusercontent.com/16047009/58432340-b110b000-80a9-11e9-8899-1f6ec7741c0c.png)
![restarts_p1d_matchedF](https://user-images.githubusercontent.com/16047009/58432342-b2da7380-80a9-11e9-9c12-56ab04607aae.png)

From these I think it looks like we can do one restart without worrying but there seems to be a bit of an effect on the IGM for more than one. What do you think?
