### ISSUE TITLE
Write a script to run GenPk on the DiRAC queue

### ISSUE THREAD

**Issue by andreufont** [andreufont/LyaCosmoParams#15]
Once we start using 1024 simulations, we'll want to run GenPk on a queue, specially if we need to run it N_sims * N_z times.

**Comment by Chris-Pedersen** [comment]
I've added some scripts to do this in: https://github.com/ucl-cosmoparticles/PedersenPhD/tree/master/DiracScripts/GenPK

These currently work on Hypatia 512s using OpenMP which makes generating the power spectra significantly faster. However I am getting seg faults running on the 1024s, even using the SMP so I need to debug this. I also will add a DiRAC script once my test run gets out of the queue.

**Comment by Chris-Pedersen** [comment]
Works on Hypatia too but only on SMP for the 1024s, GenPK crashes on smaller nodes.
