### ISSUE TITLE
Extend arxiv code to manage the new h and nu_sims

### ISSUE THREAD

**Issue by Chris-Pedersen** [andreufont/LyaCosmoParams#49]
Our new test sims will require an extension of the bookkeeping code in `p1d_arxiv` to accommodate this extended parameter space.

**Comment by Chris-Pedersen** [comment]
This is being addressed in #77 , but have some plots that would be good to have in the repo. First we look at the 0.3eV neutrino simulation. In the following plots we are looking at the emulator prediction/true P1D in the neutrino sim.

![nu_with_central](https://user-images.githubusercontent.com/16047009/88484294-7df3d600-cf65-11ea-9fbc-2a6cdc2ab1e8.png)

On first reaction here this looks too good to be true, given the predictions are genearlly <1% with very low errors. I realised that in setting up this sim, we matched the amplitude of the comoving linear power spectrum at z=3 by rescaling A_s (i.e. inverting the procedure presented in our massive neutrino paper), so the emulator calls are likely to be extremely close to one another which would explain the low uncertainty. Nevertheless, the fact that one of these simulations has massive neutrinos and the other doesn't means we are demonstrating that the P1D isn't sensitive to the neutrinos, and the parameters that we are using already capture all of the information. So this is a very strong start. To confirm the above, I remove the central LH simulation from the training set and reproduce the plot:

![nu_no_central](https://user-images.githubusercontent.com/16047009/88484296-7fbd9980-cf65-11ea-98d8-93957975becc.png)

and we see prediction accuracies and uncertainties very much in line with our other tests (i.e. ~1% predictions and low error at high z, somewhat worse performance at low z and high k). Finally just to get an idea of what the emulator parameters look like I show the emulator calls made in the plots below. The green points show the central LH simulation, the red points show the 0.3eV massive neutrino simulation, the black points show the remainder of the training data. We can see that in the linear power parameters, the red and green are almost entirely on top of each other which is also consisent with the previous 2 plots.

![nu_sim_fid](https://user-images.githubusercontent.com/16047009/88484274-4422cf80-cf65-11ea-8d2e-d3098fc7f6db.gif)
![nu_sim_fid_igm](https://user-images.githubusercontent.com/16047009/88484276-46852980-cf65-11ea-875c-9231f9f2af49.gif)

So far so good! Now I do the same thing with the h sim. NB here I think I kept Omega_mh^2 fixed from the fiducial sim and only changed H_0, but I need to double check this.

![h_with_central](https://user-images.githubusercontent.com/16047009/88484565-63226100-cf67-11ea-94dd-026436f800ae.png)
![h_no_central](https://user-images.githubusercontent.com/16047009/88484569-64ec2480-cf67-11ea-941f-d581b2bc8d11.png)

Once again I show the calls in parameter space, this time the red points show the h=0.74 simulation.

![h_sim_fid](https://user-images.githubusercontent.com/16047009/88484552-530a8180-cf67-11ea-9ac9-e02bae4afab2.gif)
![h_sim_fid_IGM](https://user-images.githubusercontent.com/16047009/88484554-543bae80-cf67-11ea-8d07-1f0d3d079620.gif)

Again we see very similar to behaviour to the case with the massive neutrino simulation, in that the emulator calls are very close to the central sim which we have modified, and they return a very similar P1D. When we remove this central sim we see emulator performance much in line with the previous tests. These plots almost seem too good to be true right now. I was expecting insensitivity to h and massive neutrinos but not quite to this degree! I will add some notebooks to the repo and keep running tests, including a sampler run. First a beer to celebrate though :smile:

**Comment by andreufont** [comment]
Hi @Chris-Pedersen , I think we can close this, addressed in PR #77
