### ISSUE TITLE
Decouple emu_kp_Mpc from like_kp_kms

### ISSUE THREAD

**Issue by andreufont** [andreufont/LyaCosmoParams#55]
In the current code we assume that these pivot points are the same, and use the fiducial value of H(z=3) to relate both. But really these could be different, and it would be clearer if we made that explicit in the code by using different variable names.

This is related to Issue #48

**Comment by andreufont** [comment]
Also related to Issue #46

**Comment by andreufont** [comment]
I'm addressing this on the kp_change branch:
 - I made a LinearPowerModel_kms object, that is a copy of LinearPowerModel but only knows how to deal with things in km/s. This is an object in the likelihood subfolder, and it is only used by recons_cosmo, mostly in the LyaTheory object and in the user interface. 
 - The old object is now called LinearPowerModel_Mpc, and it only knows how to deal with the Mpc. My goal is to eventually delete this object, but it is still alive because the code to setup the simulations use it.
 - The emulator calls also need to fit linear power at different z, in Mpc, but that does not need to be in an object. These can be just functions that anyone can call at any time.  

There are two places where the LinearPowerModel_Mpc (LPM_Mpc) object is being used in the simulations setup now:
 (A) We are defining the simulation parameters in Mpc (not sure why), so we need a LPM_Mpc object to convert the values of (Delta_star, n_star, Omega_star) to a cosmology that can be written into GenIC and Gadget files. 
 (B) We are also using these objects to compute the linear parameters for each snapshot, of each simulation, i.e., to label the training points in the emulator. 

(A) only matters to setup the simulations, so it is ok if we now change and decide to setup the next suite of simulations slightly differently. For instance, if I was to run a new suite of simulations, I'd probably setup the simulation parameters in km/s, just like we do in the likelihood parameters. Using Delta_star for something defined in Mpc it is just confusing, and unnecessary.

(B) this is more important, since it would affect how we use the emulators that we have already ran. However, I don't think we need to change the way we label the training points, all we need is to be able to compute these linear power parameters at each z, in Mpc, from the information in the Gadget / GenIC files. There is no need to use compressed parameters at all. We could just change (trivially) the post-processing code to get the linear power parameters from CAMB_model, just like we do in the FullTheory.

If you agree, I will do these changes in the branch. We can worry about merging later on. But I wanted to cross-check that the plan makes sense, and that I'm not missing anything critical here.

**Comment by andreufont** [comment]
By the way, the more I look at the current code, the more important I think it is to do the changes in this branch. We have so many values of kp in the current code (the one in the simulation parameters is not the same than in the emulator, that is not the same than in the likelihood), and we do not do systematic checks to make sure that we know which one we are using at each point.

**Comment by andreufont** [comment]
May be using k_star for the pivot point in the likelihood, in km/s, might be useful to distinguish it from k_p in the emulator, in Mpc. We could then remember that _star always refers to things in km/s at z_star=3, while _p refers to things in Mpc at different z.

**Comment by Chris-Pedersen** [comment]
That notation sounds very sensible. If you make a PR when its ready I'd be very happy to take a look! I've also needed to do some restructuring of the way our linear power spectra are calculated in order to speed up our use of `CAMB` for the importance sampling, it might be better if I do that after your changes though.

**Comment by Chris-Pedersen** [comment]
Fixed in #59
