### ISSUE TITLE
Clarify usage of free parameters in likelihood

### ISSUE THREAD

**Issue by andreufont** [andreufont/LyaCosmoParams#60]
We have free_params, free_param_limits, free_parameters, and it is not clear which are which. We should give better names, and add more comments.

**Comment by Chris-Pedersen** [comment]
I just came across a bug (responsible for the bad ordering of names in the sampler results with H0 I showed earlier) in that the ordering of like.free_params and like.free_parameters can be different, which screws up the plot labels and sampler bookkeeping. I propose we drop like.free_parameters, just have it an an argument which sets the ordering of like.free_params, but we don't store it as part of the object. We can replace with a method to return a parameter list constructed from like.free_params instead. I'll make a PR.

**Comment by Chris-Pedersen** [comment]
Fixed in #72
