### ISSUE TITLE
modify CAMB_model to only call CAMB if transfer function is different

### ISSUE THREAD

**Issue by andreufont** [andreufont/LyaCosmoParams#61]
We could sample the primordial power (As,ns) without having to call CAMB.

**Comment by Chris-Pedersen** [comment]
Just so we have this documented on the repo, on sim#3 in the Aus20 suite recovers the following primordial power constraints:

![cmb_params](https://user-images.githubusercontent.com/16047009/87035227-efe7c380-c1e0-11ea-8974-578cecbdeefd.png)
