### ISSUE TITLE
Parameter constraints get worse instead of improving when switching from PD2013 to Chabanier2019 data covmats

### ISSUE THREAD

**Issue by Chris-Pedersen** [andreufont/LyaCosmoParams#82]
As shown in https://github.com/andreufont/LyaCosmoParams/blob/minor_sampler_fixes/lya_sampler/notebooks/fstar_gstar.ipynb. The k and z binning is the same in each. I guess its possible that the Chabanier covmat has more significant off diagonals that we don't see in the results plot, but it's more likely we have some issue somewhere.

**Comment by andreufont** [comment]
This is strange... A couple of suggestions:
 - You can also artificially reduce the covariance matrix by using data_cov_factor, right? You could overplot the contours when using the PD2013 covariance artificially reduced, or the Chabanier's one artificially enlarged.
 - Have you overplot two of the covariance / correlation matrices? Are they that different?

**Comment by andreufont** [comment]
I'll take a look at the loading of the matrices

**Comment by andreufont** [comment]
I found and fixed a couple of bugs in the way we were reading the P1D covariances in #86
