### ISSUE TITLE
Role of the fiducial cosmology in the likelihood object

### ISSUE THREAD

**Issue by Chris-Pedersen** [andreufont/LyaCosmoParams#83]
Currently the fiducial cosmology serves a number of purposes when creating a likelihood object, and we do not necessarily want it to do all of these. It:

1. Sets the H(z) used to convert from comoving to velocity units (when H(z) is not being varied)
2. Sets the fiducial linear power spectrum that is rescaled when sampling primordial power spectra without calling `CAMB` for new transfer functions
3. Sets the central value of the prior distribution when a Gaussian prior is used
4. Sets the 'truth' values that are shown in corner plots

Our current setup uses the mock simulation paramfile to set up a fiducial cosmology. We probably want to decouple 1. and 2. and fix these to the cosmology in our central LH sim by default instead of taking these from the mock sim. I'm generally only running with uniform priors now, but I think we can keep using the mock sim as the centre of any Gaussian priors. So how about in future we fix 1. and 2. to our central LH sim, and only use the mock simulation cosmology for 3. and 4.?

**Comment by andreufont** [comment]
I think I agree with all your points. The important thing to remember is that we should be insensitive to the fiducial cosmology, and that the code should run when we do not have a "truth" to setup priors or similar.

**Comment by Chris-Pedersen** [comment]
FIxed in #85
